name: 'Hola mundo Actions GH'

on: 
    push:
        branches:
            - main

jobs: 
    hola_mundo:
            name: Imrpimir Hola mundo 
            runs-on: self-hosted
            steps:
                - name: Revisar el repo
                uses: actions/checkout@v2

                - name: install Pandas
                run: pip install pandas

                - name: Ejecutar codigo de python
                run: python app.py
