name: Hola mundo actions GH


on:
    push:
        branches:
            -main

jobs:
    hola_mundo:
        name: Imprimir Hola mundo
        runs-on: ubuntu-latest
        steps:
            - name: Revisar el repo
            uses: actions/chrckout@v2

            - name: Ejecutar codigo de python
            run: python app.py
