name: 'Hola mundo Actions GH'

on: 
    push:
        branches:
            - main

jobs: 
    hola_mundo:
        name: Imrpimir Hola mundo 
        runs-on: ubuntu-latest
        steps:
            - name: Revisar el repo
              uses: actions/checkout@v2

            - name: install libs
              run: pip install -r requirements.txt

            - name: Ejecutar codigo de python
              run: python app.py
